[package]
name = "rust_queue_test"
version = "0.1.0"
authors = ["Test <test@example.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"